meta_product_name: "BALMORAL"
meta_title: "Balmoral - Votre maison de famille, c'est que du bonheur !"
meta_description: "Balmoral offre une solution facile et transparente de gérer une maison de famille."
meta_image: "main_image.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
